development:
  adapter: postgresql
  database: movie_lister_development
  host: localhost
  min_messages: WARNING
  username: root
  password: abcd12
test:
  adapter: postgresql
  database: movie_lister_test
  host: localhost
  min_messages: WARNING
  username: root
  password: abcd12
